export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_ERROR = 'ADVERTS_LOADED_SUCCESS';


export const ADVERTS_CREATED_REQUEST = 'ADVERTS_CREATED_REQUEST';
export const ADVERTS_CREATED_SUCCESS = 'ADVERTS_CREATED_SUCCESS';
export const ADVERTS_CREATED_ERROR = 'ADVERTS_CREATED_ERROR';


export const ADVERTS_DELETED_REQUEST = 'ADVERTS_DELETED_REQUEST';
export const ADVERTS_DELETED_SUCCESS = 'ADVERTS_DELETED_SUCCESS';
export const ADVERTS_DELETED_ERROR = 'ADVERTS_DELETED_ERROR';

export const ADVERTS_DETAIL_SUCCESS = 'ADVERTS_DETAIL_SUCCESS';

export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST';
export const TAGS_LOADED_SUCCESS = 'TAGS_LOADED_SUCCESS';
export const TAGS_LOADED_ERROR = 'TAGS_LOADED_SUCCESS';

